// src/components/Leaderboard.jsx
import React, { Component } from 'react';

class Leaderboard extends Component {
    state = {  }
    render() { 
        return ( 
            <div className="container" style={{'margin-top': '20px'}}>
                <h1>Leaderboard</h1>
                <div className="card text-center">
                    <div className="card-header">
                    <ul className="nav nav-pills card-header-pills">
                        <li className="nav-item">
                        <a className="nav-link">SIA</a>
                        </li>
                        <li className="nav-item">
                        <a className="nav-link">My Friends</a>
                        </li>
                        <li className="nav-item">
                        <a className="nav-link">My Family</a>
                        </li>
                    </ul>
                    </div>
                    <div className="card-body">
                    <table className="table table-striped">
                        <thead>
                        <tr>
                            <th scope="col">Rank</th>
                            <th scope="col">Name</th>
                            <th scope="col">Return</th>
                            <th scope="col">Top Performer</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <th scope="row">1</th>
                            <td>Mark</td>
                            <td>+25%</td>
                            <td>Tesla (TSLA)</td>
                        </tr>
                        <tr>
                            <th scope="row">2</th>
                            <td>Jacob</td>
                            <td>+5%</td>
                            <td>Palantir (PLTR)</td>
                        </tr>
                        <tr>
                            <th scope="row">3</th>
                            <td>Brandon</td>
                            <td>-10%</td>
                            <td>Amazon (AMZN)</td>
                        </tr>
                        </tbody>
                    </table>
                    <table className="table table-striped">
                        <thead>
                        <tr>
                            <th scope="col">Rank</th>
                            <th scope="col">Name</th>
                            <th scope="col">Return</th>
                            <th scope="col">Top Performer</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <th scope="row">1</th>
                            <td>Parker</td>
                            <td>+25%</td>
                            <td>Tesla (TSLA)</td>
                        </tr>
                        <tr>
                            <th scope="row">2</th>
                            <td>Adwait</td>
                            <td>+5%</td>
                            <td>Palantir (PLTR)</td>
                        </tr>
                        <tr>
                            <th scope="row">3</th>
                            <td>Brandon</td>
                            <td>-10%</td>
                            <td>Amazon (AMZN)</td>
                        </tr>
                        </tbody>
                    </table>
                    <table className="table table-striped">
                        <thead>
                        <tr>
                            <th scope="col">Rank</th>
                            <th scope="col">Name</th>
                            <th scope="col">Return</th>
                            <th scope="col">Top Performer</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <th scope="row">1</th>
                            <td>Bernard</td>
                            <td>+25%</td>
                            <td>Tesla (TSLA)</td>
                        </tr>
                        <tr>
                            <th scope="row">2</th>
                            <td>Stacy</td>
                            <td>+5%</td>
                            <td>Palantir (PLTR)</td>
                        </tr>
                        <tr>
                            <th scope="row">3</th>
                            <td>Brandon</td>
                            <td>-10%</td>
                            <td>Amazon (AMZN)</td>
                        </tr>
                        </tbody>
                    </table>
                    </div>
                </div>
                </div>
        );
    }
}
 
export default Leaderboard;

// src/app/leaderboard/leaderboard.component.ts
import { HttpClient, HttpClientModule, HttpHeaders, HttpParams } from '@angular/common/http';
import { Component, OnInit, Injectable } from '@angular/core';
import { Observable, throwError } from "rxjs";
import { catchError, retry } from "rxjs/operators";

@Component({
  selector: 'app-leaderboard',
  templateUrl: './leaderboard.component.html',
  styleUrls: ['./leaderboard.component.css']
})
export class LeaderboardComponent{

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="container" style="margin-top: 20px;">
  <h1>Leaderboard</h1>
  <div class="card text-center">
    <div class="card-header">
      <ul class="nav nav-pills card-header-pills">
        <li class="nav-item">
          <a class="nav-link active" href="#">SIA</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">My Friends</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">My Family</a>
        </li>
      </ul>
    </div>
    <div class="card-body">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Rank</th>
            <th scope="col">Name</th>
            <th scope="col">Return</th>
            <th scope="col">Top Performer</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">1</th>
            <td>Mark</td>
            <td>+25%</td>
            <td>Tesla (TSLA)</td>
          </tr>
          <tr>
            <th scope="row">2</th>
            <td>Jacob</td>
            <td>+5%</td>
            <td>Palantir (PLTR)</td>
          </tr>
          <tr>
            <th scope="row">3</th>
            <td>Brandon</td>
            <td>-10%</td>
            <td>Amazon (AMZN)</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
