// src/components/Profile.jsx
import React, { Component } from 'react';

class Profile extends Component {
    state = {  }
    render() { 
        return ( <div className="container" style={{'margin-top': '20px'}}>
        <h1>Profile</h1>
        <div className="card">
            <div className="card-body">
              <div className="border-bottom text-center pb-4">
                <img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="profile" className="img-sm rounded-circle" />
                <div className="mb-3">
                  <h3>Brandon Kung</h3>
                  <div className="d-flex align-items-center justify-content-center">
                    <h5 className="mb-0 mr-2 text-muted">USA</h5>
                    <div className="br-wrapper br-theme-css-stars"><select id="profile-rating" name="rating" autocomplete="off" style={{'display': 'none'}}>
                      <option value="1">1</option>
                      <option value="2">2</option>
                      <option value="3">3</option>
                      <option value="4">4</option>
                      <option value="5">5</option>
                    </select><div className="br-widget"><a href="#" data-rating-value="1" data-rating-text="1" className="br-selected br-current"></a><a href="#" data-rating-value="2" data-rating-text="2"></a><a href="#" data-rating-value="3" data-rating-text="3"></a><a href="#" data-rating-value="4" data-rating-text="4"></a><a href="#" data-rating-value="5" data-rating-text="5"></a></div></div>
                  </div>
                </div>
                <p className="w-75 mx-auto mb-3">Michigan State University</p>
                <div className="d-flex justify-content-center">
                  <button className="btn btn-success mr-1">Portfolio</button>
                  <button className="btn btn-success">My Groups</button>
                </div>
              </div>
              <div className="container">
                <h3>Stocks</h3>
              </div>
              <div className="border-bottom py-4">
                <div>
                  <ul className="list-group list-group-flush">
                      <li>Stonk</li>
                  </ul>
                </div>                                                               
              </div>
              <div className="border-bottom py-4">
                <div className="d-flex mb-3">
                  <div className="progress progress-md flex-grow">
                    <div className="progress-bar bg-primary" role="progressbar" aria-valuenow="55" style={{'width': '55%'}} aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                </div>
                <div className="d-flex">
                  <div className="progress progress-md flex-grow">
                    <div className="progress-bar bg-success" role="progressbar" aria-valuenow="75" style={{'width': '75%'}} aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                </div>
              </div>
              <div className="py-4">
                <p className="clearfix">
                  <span className="float-left">
                    Rank
                  </span>
                  <span className="float-right text-muted">
                    Beginner
                  </span>
                </p>
                <p className="clearfix">
                  <span className="float-left">
                    Phone
                  </span>
                  <span className="float-right text-muted">
                    006 3435 22
                  </span>
                </p>
                <p className="clearfix">
                  <span className="float-left">
                    Mail
                  </span>
                  <span className="float-right text-muted">
                    Jacod@testmail.com
                  </span>
                </p>
                <p className="clearfix">
                  <span className="float-left">
                    Facebook
                  </span>
                  <span className="float-right text-muted">
                    <a href="#">David Grey</a>
                  </span>
                </p>
                <p className="clearfix">
                  <span className="float-left">
                    Twitter
                  </span>
                  <span className="float-right text-muted">
                    <a href="#">@davidgrey</a>
                  </span>
                </p>
              </div>
              <button className="btn btn-primary btn-block mb-2">Preview</button>
              <div id="container-fastlink">
                <div style={{'text-align': 'center'}}>
                 <input type="submit" id="btn-fastlink" value="Link an Account" />
                </div>
              </div>
            </div>
          </div>
    </div> );
    }
}
 
export default Profile;

// src/app/profile/profile.component.ts
import { Stock } from './../../types/stock';
import { HttpClient, HttpClientModule, HttpHeaders, HttpParams, HttpClientJsonpModule } from '@angular/common/http';
import { Component, OnInit, Injectable } from '@angular/core';
import { Observable, throwError } from "rxjs";
import { catchError, retry } from "rxjs/operators"; 

@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.css']
})
export class ProfileComponent {
  stocks: any = [];

  constructor(private http: HttpClient) {

    const headers = { 
      'API-VERSION': '1.1', 
      'Content-Type': 'application/json', 
      'Authorization': 'Bearer 5BAUcmmHUG4veKewj7xvp7FklUpg'
    };

    http.get('https://development.api.yodlee.com/ysl/holdings?accountId=10297472&providerAccountId=10069444', {headers})
    .subscribe(response =>
       this.stocks = response
       )
  }

  ngOnInit(): void {
  }

}

<div class="container" style="margin-top: 20px;">
    <h1>Profile</h1>
    <div class="card">
        <div class="card-body">
          <div class="border-bottom text-center pb-4">
            <img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="profile" class="img-sm rounded-circle">
            <div class="mb-3">
              <h3>Brandon Kung</h3>
              <div class="d-flex align-items-center justify-content-center">
                <h5 class="mb-0 mr-2 text-muted">USA</h5>
                <div class="br-wrapper br-theme-css-stars"><select id="profile-rating" name="rating" autocomplete="off" style="display: none;">
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                  <option value="4">4</option>
                  <option value="5">5</option>
                </select><div class="br-widget"><a href="#" data-rating-value="1" data-rating-text="1" class="br-selected br-current"></a><a href="#" data-rating-value="2" data-rating-text="2"></a><a href="#" data-rating-value="3" data-rating-text="3"></a><a href="#" data-rating-value="4" data-rating-text="4"></a><a href="#" data-rating-value="5" data-rating-text="5"></a></div></div>
              </div>
            </div>
            <p class="w-75 mx-auto mb-3">Michigan State University</p>
            <div class="d-flex justify-content-center">
              <button class="btn btn-success mr-1">Portfolio</button>
              <button class="btn btn-success">My Groups</button>
            </div>
          </div>
          <div class="border-bottom py-4">
            <p>Stocks</p>
            <div>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">Facebook</li>
                <li class="list-group-item">Apple</li>
                <li class="list-group-item">Netflix</li>
                <li class="list-group-item">Google</li>
                <li class="list-group-item">Amazon</li>
              </ul>  
            </div>                                                               
          </div>
          <div class="border-bottom py-4">
            <div class="d-flex mb-3">
              <div class="progress progress-md flex-grow">
                <div class="progress-bar bg-primary" role="progressbar" aria-valuenow="55" style="width: 55%" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>
            <div class="d-flex">
              <div class="progress progress-md flex-grow">
                <div class="progress-bar bg-success" role="progressbar" aria-valuenow="75" style="width: 75%" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>
          </div>
          <div class="py-4">
            <p class="clearfix">
              <span class="float-left">
                Rank
              </span>
              <span class="float-right text-muted">
                Beginner
              </span>
            </p>
            <p class="clearfix">
              <span class="float-left">
                Phone
              </span>
              <span class="float-right text-muted">
                006 3435 22
              </span>
            </p>
            <p class="clearfix">
              <span class="float-left">
                Mail
              </span>
              <span class="float-right text-muted">
                Jacod@testmail.com
              </span>
            </p>
            <p class="clearfix">
              <span class="float-left">
                Facebook
              </span>
              <span class="float-right text-muted">
                <a href="#">David Grey</a>
              </span>
            </p>
            <p class="clearfix">
              <span class="float-left">
                Twitter
              </span>
              <span class="float-right text-muted">
                <a href="#">@davidgrey</a>
              </span>
            </p>
          </div>
          <button class="btn btn-primary btn-block mb-2">Preview</button>
          <ul class="list-group">
            <li 
            *ngFor="let stock of stocks"
            class="list-group-item">
          {{ stock.symbol }}
          </li>
          </ul>
        </div>
      </div>
</div>
